services:
  
  # Applications =============================================== 

  code.executor.auth:
    image: codeexecutor.auth.host
    depends_on:
      - db
      - jaeger
    ports:
      - "127.0.0.1:5020:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80/
      - Database__PostgreSql=Host=db;Port=5432;Database=postgres;Username=postgres;Password=1
      - Telemetry__Tracing__ExporterUrl=http://oltp:4317
      - Telemetry__Tracing__UseHttpTracing=true
      - Telemetry__Tracing__UseSqlTracing=true
    build:
      context: .
      dockerfile: Auth/CodeExecutor.Auth.Host/Dockerfile
    volumes:
      - auth:/var/lib/code.executor.auth/data
    networks:
      - backend
  
  code.executor.dispatcher:
    image: codeexecutor.dispatcher.host
    depends_on:
      - db
      - rabbitmq
      - jaeger
    ports:
      - "127.0.0.1:5030:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80/
      - Database__PostgreSql=Host=db;Port=5432;Database=postgres;Username=postgres;Password=1
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=rmuser
      - RabbitMq__Password=rmpassword
      - Telemetry__Tracing__ExporterUrl=http://oltp:4317
      - Telemetry__Tracing__UseHttpTracing=true
      - Telemetry__Tracing__UseSqlTracing=true
    build:
      context: .
      dockerfile: Dispatcher/CodeExecutor.Dispatcher.Host/Dockerfile
    volumes:
      - dispatcher:/var/lib/code.executor.dispatcher/data
    networks:
      - backend
  
  csharp.executor:
    image: csharpexecutor
    depends_on:
      - code.executor.dispatcher
      - rabbitmq
      - jaeger
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:81/
      - Api__DispatcherUrl=http://code.executor.dispatcher:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=rmuser
      - RabbitMq__Password=rmpassword
      - Telemetry__Tracing__ExporterUrl=http://oltp:4317
      - Telemetry__Tracing__UseHttpTracing=true
    build:
      context: .
      dockerfile: Executors/CSharpCodeExecutor/Dockerfile
    volumes:
      - executors:/var/lib/csharp12.executor/data
    networks:
      - backend
  
  # Infrastructure =============================================== 
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    networks:
      backend:
        aliases:
          - jaeger
          - oltp

  zookeeper:
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - backend
      

volumes:
  db:
  pgadmin:
  rabbitmq:
  dispatcher:
  auth:
  executors:
    
networks:
  backend: