services:
  
  # Applications =============================================== 

  code.executor.auth:
    image: codeexecutor.auth.host
    hostname: code.executor.auth
    depends_on:
      - postgres
    ports:
      - 5020:80/tcp
      - 5021:443/tcp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - Database__PostgreSql="Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=1"
    build:
      context: .
      dockerfile: Auth/CodeExecutor.Auth.Host/Dockerfile
    volumes:
      - auth:/var/lib/code.executor.auth/data
    networks:
      - backend
  
  code.executor.dispatcher:
    image: codeexecutor.dispatcher.host
    hostname: code.executor.dispatcher
    depends_on:
      - postgres
      - rabbitmqx
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - Database__PostgreSql="Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=1"
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=rmuser
      - RabbitMq__Password=rmpassword
    build:
      context: .
      dockerfile: Dispatcher/CodeExecutor.Dispatcher.Host/Dockerfile
    volumes:
      - dispatcher:/var/lib/code.executor.dispatcher/data
    networks:
      - backend
  
  csharp.executor:
    image: csharpexecutor
    depends_on:
      - rabbitmq
    environment:
      - Api__DispatcherUrl=http://code.executor.dispatcher:5030
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=rmuser
      - RabbitMq__Password=rmpassword
      - HealthCheck__TestApi=true
    build:
      context: .
      dockerfile: Executors/CSharpCodeExecutor/Dockerfile
    volumes:
      - executors:/var/lib/csharp12.executor/data
    networks:
      - backend
  
  # Infrastructure =============================================== 
  
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend

volumes:
  postgres:
  pgadmin:
  rabbitmq:
  dispatcher:
  auth:
  executors:
    

networks:
  backend: