global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using CodeExecutor.Common.Models.Exceptions;
global using CodeExecutor.Dispatcher.Contracts;
global using DbModel = CodeExecutor.DB.Abstractions.Models;
global using DbRepository = CodeExecutor.DB.Abstractions.Repository;
global using Messaging = CodeExecutor.Messaging;