global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Logging;
global using CodeExecutor.Dispatcher.Contracts;
global using CodeExecutor.Common.Models.Exceptions;
global using DbRepository = CodeExecutor.DB.Abstractions.Repository;