openapi: 3.0.1
info:
  title: dotnet-swagger
  version: v1
paths:
  /codeexecutions/execute:
    post:
      tags:
        - CodeExecutions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeExecutionRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CodeExecutionRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CodeExecutionRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CodeExecutionStartResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CodeExecutionStartResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CodeExecutionStartResponse'
  '/codeexecutions/result/{guid}':
    get:
      tags:
        - CodeExecutions
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CodeExecutionExpanded'
            application/json:
              schema:
                $ref: '#/components/schemas/CodeExecutionExpanded'
            text/json:
              schema:
                $ref: '#/components/schemas/CodeExecutionExpanded'
  '/codeexecutions/sourcecode/{guid}':
    get:
      tags:
        - CodeExecutions
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SourceCode'
            application/json:
              schema:
                $ref: '#/components/schemas/SourceCode'
            text/json:
              schema:
                $ref: '#/components/schemas/SourceCode'
  /codeexecutions/list:
    get:
      tags:
        - CodeExecutions
      parameters:
        - name: skip
          in: query
          schema:
            type: integer
            format: int32
        - name: take
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeExecution'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeExecution'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeExecution'
  '/codeexecutions/delete/{guid}':
    delete:
      tags:
        - CodeExecutions
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
  /codeexecutionsmodification/setresult:
    patch:
      tags:
        - CodeExecutionsModification
      parameters:
        - name: validationTag
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeExecutionResult'
          text/json:
            schema:
              $ref: '#/components/schemas/CodeExecutionResult'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CodeExecutionResult'
      responses:
        '200':
          description: Success
  /languages/list:
    get:
      tags:
        - Languages
      parameters:
        - name: skip
          in: query
          schema:
            type: integer
            format: int32
        - name: take
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /languages/listversions:
    get:
      tags:
        - Languages
      parameters:
        - name: languageName
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    CodeExecution:
      required:
        - guid
        - isError
        - language
        - requestedAt
      type: object
      properties:
        guid:
          type: string
          format: uuid
        language:
          $ref: '#/components/schemas/Language'
        requestedAt:
          type: string
          format: date-time
        startedAt:
          type: string
          format: date-time
          nullable: true
        finishedAt:
          type: string
          format: date-time
          nullable: true
        comment:
          type: string
          nullable: true
        isError:
          type: boolean
      additionalProperties: false
    CodeExecutionExpanded:
      required:
        - guid
        - isError
        - language
        - requestedAt
      type: object
      properties:
        guid:
          type: string
          format: uuid
        language:
          $ref: '#/components/schemas/Language'
        requestedAt:
          type: string
          format: date-time
        startedAt:
          type: string
          format: date-time
          nullable: true
        finishedAt:
          type: string
          format: date-time
          nullable: true
        comment:
          type: string
          nullable: true
        isError:
          type: boolean
        data:
          type: string
          nullable: true
        sourceCode:
          type: string
          nullable: true
      additionalProperties: false
    CodeExecutionRequest:
      required:
        - codeText
        - languageId
      type: object
      properties:
        codeText:
          minLength: 1
          type: string
        languageId:
          type: integer
          format: int64
        priority:
          $ref: '#/components/schemas/ExecutionPriority'
      additionalProperties: false
    CodeExecutionResult:
      type: object
      properties:
        guid:
          type: string
          format: uuid
        data:
          type: string
          nullable: true
        comment:
          type: string
          nullable: true
        isError:
          type: boolean
          nullable: true
      additionalProperties: false
    CodeExecutionStartResponse:
      required:
        - guid
      type: object
      properties:
        guid:
          type: string
          format: uuid
        comment:
          type: string
          nullable: true
      additionalProperties: false
    ExecutionPriority:
      enum:
        - 0
        - 1
        - 2
        - 3
      type: integer
      format: int32
    Language:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          minLength: 1
          type: string
        version:
          type: string
          nullable: true
      additionalProperties: false
    SourceCode:
      type: object
      properties:
        text:
          type: string
          nullable: true
        languageId:
          type: integer
          format: int64
      additionalProperties: false